spring:
  application:
    name: customer

base:
  location: http://localhost:8080

server:
  port: 8081

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true